# Explanatory examples
The examples below are created with the intent to help understand how to use the functions and classes in this repo.

In [1]:
import mappings
import get_instances
import solver

## Load an instance configuration
Load an instance from the folder `instances`

In [2]:
example_filename = 'lss_ne6.csv_11_29_nbcfeas_scn0.txt'
example_instance = get_instances.create_single_instance(
    instance_filename=example_filename,
    relaxed=False,
)
print(example_instance)

LsssdInstance(name='lss_ne6.csv_11_29_nbcfeas_scn0', numOfPorts=12, ports=array(['CNTAO', 'KRKAN', 'KRPUS', 'CNSHA', 'CNYTN', 'SGSIN', 'EGSUZ',
       'ESALG', 'DEHAM', 'NLRTM', 'FRLEH', 'CNTAO'], dtype='<U5'), timeWindowStart=array([134.,  24.,  49., 103.,  13., 113.,  97.,  67.,  23.,  95., 150.,
       134.]), timeWindowEnd=array([154.,  39.,  72., 127.,  27., 135., 115.,  82.,  63., 128., 174.,
       154.]), fixedSailingCost=array([[      0.  ,   52388.55,   61842.6 ,   49892.85,  139970.7 ,
         306801.9 ,  950142.6 , 1169341.2 , 1373375.25, 1341163.8 ,
        1316143.35,       0.  ],
       [  51457.95,       0.  ,    9009.9 ,   48073.95,  133794.9 ,
         316700.1 ,  958095.  , 1206417.15, 1453999.05, 1376442.  ,
        1352013.75,   51457.95],
       [  61842.6 ,    9009.9 ,       0.  ,   61081.2 ,  142952.85,
         311285.7 ,  963763.2 , 1173825.  , 1377859.05, 1345647.6 ,
        1320627.15,   61842.6 ],
       [  49892.85,   50865.75,   61081.2 ,       0.  ,  10

## Map portorder to ideal solution

To map a portorder to its ideal solution, first an instance of the Model class is created.

In [3]:
example_model = mappings.Model3( # also valid: Model1 or Model2
    instance=example_instance,
    distribution='genlog_3p', # also valid: 'deterministic' or 'normal'
    service_level='0.9000', # Also valid: 0.7000 or 0.9500 (only genlog_3p)
)
print(example_model)

Then a portorder is chosen and its optimal solution is created.

The solution object uses only the objective value and the portorder in its representation.
Information about the schedule and the transported demands can be accessed as shown below.

In [4]:
example_portorder = (0,1,2,3,4,5,6,7,8,9,10,0)
example_sol = example_model.generate_solution(x=example_portorder)
print(example_sol)
print(example_sol.schedule.w)
print(example_sol.schedule.tau_a)
print(example_sol.schedule.tau_s)
print(example_sol.schedule.tau_e)
print(example_sol.y)


Model3Solution(obj_value=np.float64(9951354.364505803), x=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0]))
[ 0  2  3  4  6  8 11 13 15 16 17 23]
[   0.          189.09083333  381.035       616.91333333  868.07666667
 1155.9975     1907.45666667 2131.99416667 2403.16166667 2608.585
 2836.83916667 3911.5775    ]
[ 134.  360.  553.  775. 1021. 1457. 1945. 2251. 2543. 2783. 3006. 3998.]
[ 154.  375.  576.  799. 1035. 1479. 1963. 2266. 2583. 2816. 3030. 4018.]
[False False False False False False False  True False False False False
 False False False False False False False False False False False False
 False False False  True False]


## Find optimal portorder

### Steepest 3opt Descent

In [5]:
s3d_solver = solver.LSSolverSteepest3opt(model = example_model)
s3d_result = s3d_solver.solve()
s3d_result[0]


Model3Solution(obj_value=np.float64(5993982.387930944), x=array([ 0,  1,  2, 10,  9,  8,  7,  6,  5,  4,  3,  0]))

### First 2Hopt Descent

In [6]:
f2hd_solver = solver.LSSolverFirst2Hopt(model = example_model)
f2hd_result = f2hd_solver.solve()
f2hd_result[0]

Model3Solution(obj_value=np.float64(5993982.387930944), x=array([ 0,  1,  2, 10,  9,  8,  7,  6,  5,  4,  3,  0]))

### Tabu Search

In [7]:
tabu_solver = solver.TabuSolver(model = example_model, max_runtime=100)
tabu_result = tabu_solver.solve()
tabu_result[0]

Model3Solution(obj_value=np.float64(5831424.076462179), x=array([ 0,  2,  6,  9,  8, 10,  7,  5,  4,  3,  1,  0]))

### ILS

In [8]:
ils_solver = solver.ILSSolver(model = example_model, max_runtime=100)
ils_result = ils_solver.solve()
ils_result[0]

Model3Solution(obj_value=np.float64(5831424.076462179), x=array([ 0,  2,  6,  9,  8, 10,  7,  5,  4,  3,  1,  0]))